name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.7
      - run: ko build
